# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b0873cef4c8e64c4f4b30ffc8233dd2309eb6e572e774bda8c2e556551d0805efd45a3fc0a1148e43e88106e3f24f6422fc47b274d135e323eb1d2774bdc61

test:
  secret_key_base: 2628b49ba4e2033e6b5724757380e323855b0edb06d8d304a02889df0fa3856a5264584a7f5327f709defaa122df960ed467accd43b1b3dca6c0901c3d640dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
